version: "3.7"

services:
  db:
    image: postgres:14
    container_name: sunsurfers_tg_bot
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sunsurfers_tg_bot"
      POSTGRES_USER: "ИМЯ ПОЛЬЗОВАТЕЛЯ"
      POSTGRES_PASSWORD: "ПАРОЛЬ"

  bot:
    build: .
    command: python main.py
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

volumes:
  pgdata: