version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: sunsurfers_tg_bot
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    command: python main.py
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

volumes:
  pgdata: