import logging
import psycopg2

from settings.config import HOST, POSTGRESQL_USER, POSTGRESQL_PASSWORD, DATABASE

logger = logging.getLogger("bot.data.create_db")


class Database:

    def __init__(self):
        self.connection = psycopg2.connect(host=HOST,
                                           user=POSTGRESQL_USER,
                                           password=POSTGRESQL_PASSWORD,
                                           database=DATABASE)
        self.connection.autocommit = True

    def new_table_users(self):
        logger.debug('Starting the creation of a new user table')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS users 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about text,
                    country character varying(255),
                    state character varying(255),
                    city character varying(255),
                    address character varying(255),
                    latitude character varying(255),
                    longitude character varying(255),
                    updated_location timestamp without time zone,
                    ban integer DEFAULT 0,
                    CONSTRAINT users_pkey PRIMARY KEY (id)
                );"""
            )

    def new_table_sun_gathering_1(self):
        logger.debug('Starting the creation of a new table of SunGathering Thailand')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Thailand 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_2(self):
        logger.debug('Starting the creation of a new table of SunGathering India')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_India 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_3(self):
        logger.debug('Starting the creation of a new table of SunGathering Vietnam')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Vietnam 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_4(self):
        logger.debug('Starting the creation of a new table of SunGathering Philippines')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Philippines 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_5(self):
        logger.debug('Starting the creation of a new table of SunGathering Georgia')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Georgia 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_6(self):
        logger.debug('Starting the creation of a new table of SunGathering Indonesia')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Indonesia 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_7(self):
        logger.debug('Starting the creation of a new table of SunGathering Nepal')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Nepal 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_8(self):
        logger.debug('Starting the creation of a new table of SunGathering Morocco')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Morocco 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_9(self):
        logger.debug('Starting the creation of a new table of SunGathering Turkey')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Turkey 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_10(self):
        logger.debug('Starting the creation of a new table of SunGathering Mexico')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_Mexico 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )

    def new_table_sun_gathering_11(self):
        logger.debug('Starting the creation of a new table of SunGathering SriLanka')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS sun_gathering_SriLanka 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    username character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about_sun_gathering text
                );"""
            )


db_obj = Database()
db_obj.new_table_users()
db_obj.new_table_sun_gathering_1()
db_obj.new_table_sun_gathering_2()
db_obj.new_table_sun_gathering_3()
db_obj.new_table_sun_gathering_4()
db_obj.new_table_sun_gathering_5()
db_obj.new_table_sun_gathering_6()
db_obj.new_table_sun_gathering_7()
db_obj.new_table_sun_gathering_8()
db_obj.new_table_sun_gathering_9()
db_obj.new_table_sun_gathering_10()
db_obj.new_table_sun_gathering_11()
