import logging
import psycopg2

from settings.config import HOST, POSTGRESQL_USER, POSTGRESQL_PASSWORD, DATABASE

logger = logging.getLogger("bot.data.create_db")


class Database:

    def __init__(self):
        self.connection = psycopg2.connect(host=HOST,
                                           user=POSTGRESQL_USER,
                                           password=POSTGRESQL_PASSWORD,
                                           database=DATABASE)
        self.connection.autocommit = True

    def new_table_users(self):
        logger.debug('Запуск создания новой таблицы пользователя')
        with self.connection.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS users 
                (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 500000 CACHE 1 ),
                    user_id bigint NOT NULL,
                    country character varying(255),
                    city character varying(255),
                    username character varying(255),
                    telephone character varying(255),
                    first_name character varying(255)NOT NULL,
                    last_name character varying(255),
                    about text,
                    latitude character varying(255),
                    longitude character varying(255),
                    ban integer DEFAULT 0,
                    CONSTRAINT users_pkey PRIMARY KEY (id)
                );"""
            )


db_obj = Database()
db_obj.new_table_users()
